/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'grahamthomson' at '8/20/19 7:29 PM' with Gradle 2.14.1
 *
 * @author grahamthomson, @date 8/20/19 7:29 PM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
