/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'grahamthomson' at '8/20/19 7:29 PM' with Gradle 2.14.1
 *
 * @author grahamthomson, @date 8/20/19 7:29 PM
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod())
  }
}
